name: knowby_api
publish_to: none
version: 0.0.0+1

environment:
  sdk: ^3.0.5

dependencies:
  freezed_annotation: ^2.2.0
  http: ^1.1.0
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  very_good_analysis: ^5.0.0+1
