name: app
publish_to: none
version: 0.0.0+1

environment:
  sdk: ^3.0.5

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  go_router: ^9.0.0
  knowby_api:
    path: ../packages/knowby_api
  logging: ^1.2.0
  shared_preferences: ^2.1.2

dev_dependencies:
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
